config/routes.rb
Folio::Application.routes.draw do
  # Handle incoming email
  mount_griddler
  
  # Handle users authentication
  devise_for :users, :path_names => {:sign_up => "register"}
  devise_scope :user do
    constraints(Subdomain) do
      get "/login" => "devise/sessions#new"
    end
  end
  get 'accounts/check_subdomain' => 'accounts#check_subdomain', :as => :check_subdomain
  
  #Restricted to subdomain
  constraints(Subdomain) do
    get 'contacts/new_from_modal' => 'contacts#new_from_modal', :as => :new_contact_from_modal
    get 'accounts/check_invoice_number_availability' => 'accounts#check_invoice_number_availability', as: :check_invoice_number_availability
    get 'invoices/:id/activate_from_modal' => 'invoices#activate_from_modal', :as => :activate_invoice_from_modal
    patch 'invoices/:id/change_status' => 'invoices#change_status', :as => :change_invoice_status
    patch 'invoices/:id/cancel' => 'invoices#cancel', :as => :cancel_invoice
    patch 'invoices/:id/pay' => "invoices#pay", :as => :pay_invoice
    patch 'invoices/:id/activate' => "invoices#activate", :as => :activate_invoice
    get 'invoices/:id/clone' => "invoices#clone", :as => :clone_invoice
    get 'invoices/:id/attachments', to: redirect("/invoices/%{id}#invoice-attachments")
    get 'dtes/status/:invoice_id' => "dtes#status", as: :status
    resources :accounts, :only => [:show, :edit, :index, :update, :check_invoice_number_availability] do

    end
    resources :dtes
    resources :expenses
    resources :users
    resources :contacts
    resources :comments
    resources :attachments
    resources :companies do
      get 'invoices', :on => :member
      get 'contacts', :on => :member
      get 'expenses', :on => :member
    end
    resources :invoices do
      get :autocomplete_company_name, :on => :collection
      collection do
        get 'active'
        get 'draft'
        get 'due'
      end
    end
    resources :money_accounts
    get '/dashboard' => 'accounts#dashboard', :as => :dashboard
    root :to => "accounts#dashboard"
  end
  
  resources :accounts, :only => [:new, :create] , :constraints => { :subdomain => /(app|www|folio)/ }
  
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  autocomplete :company, :name, :full => true, :scopes => [:for_account]
  skip_before_filter :verify_authenticity_token, :only => :change_status
  rescue_from Dte::InvalidDTE, with: :invalid_dte

  # Methods to get the invoice given their status_name
  # status_name defined in Invoice model
  Invoice::STATUS_NAME.each do |status|
    define_method "#{status}" do
      @invoices = current_account.send("#{status}_invoices")
      render "index"
    end
  end


  def activate_from_modal
    @invoice = current_account.invoices.find(params[:id])
    @invoice.attachments.build
    respond_to do |format|
      format.html {render layout: false}
      format.js {render :template => "invoice_activation_modal", layout: false}
    end
  end

  def cancel
    @invoice = current_account.invoices.find(params[:id])
    if @invoice.cancel!
      flash[:notice] = "Venta anulada"
      redirect_to invoice_path(@invoice)
    else
      flash.now[:error] = "No es posible anular esta venta."
      redirect_to invoice_path(@invoice)
    end

  end

  def activate
    @invoice = current_account.invoices.find(params[:id])
    @invoice.number = params[:number].to_i
    @invoice.active
    respond_to do |format|
    if @invoice.save && !@invoice.draft?
      format.html {
        flash[:notice] = "Venta activada correctamente."
        flash.now[:notice] << "\n Recibirá una notificación por email cuando el SII autorice la factura." if current_account.e_invoice_enabled?
        redirect_to @invoice
      }
      format.js { render 'show'}
      else
        errors = '<ul>' + @invoice.errors.messages.values.map { |v| "<li>#{v}</li>" }.join('') + '</ul>'
        format.html {
          flash[:error] = "No se pudo activar la venta<br/> #{errors}".html_safe
          redirect_to @invoice
        }
        format.js { render 'change_status_error'}
      end
    end
  end

  def clone
    source_invoice = current_account.invoices.find(params[:id])
    @invoice = source_invoice.clone!
    @invoice.attachments.build
    @invoice.build_reminder
  end

  def create
    params = prices_to_numbers
    @invoice = current_account.invoices.new(invoice_params)
    respond_to do |format|
      if @invoice.save
        flash[:notice] = "Venta guardada correctamente."
        format.html {redirect_to invoice_path(@invoice)}
        format.json
      else
        flash.now[:error] = "No pudimos guardar esta venta, por favor corrige los errores indicados."
        format.html {render 'new'}
        format.json
      end
    end
  end

  def destroy
    @invoice = current_account.invoices.find(params[:id])
    if @invoice.destroy
      flash[:notice] = "Venta borrada correctamente."
      redirect_to invoices_path()
    else
      flash[:alert] = "Sólo se pueden borrar ventas que estén en borrador."
      redirect_to @invoice
    end
  end

  def update
    params = prices_to_numbers
    @invoice = current_account.invoices.find(params[:id])
    if @invoice.update_invoice(invoice_params)
      flash.now[:notice] = "Venta actualizada correctamente"
      redirect_to invoice_path(@invoice)
    else
      flash.now[:error] = "No pudimos guardar esta venta, por favor corrige los errores indicados."
      render 'edit'
    end
  end

  def edit
    @invoice = current_account.invoices.find(params[:id])
  end

  def index
    @invoices_total_resume = @current_account.invoices_search(params[:search])
    @invoices = @invoices_total_resume.page(params[:page])
    params.delete(:controller)
    params.delete(:action)
    params.delete("_")
    @search_params = params.to_param
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @invoice = current_account.invoices.new
    @invoice.invoice_items.build
    @invoice.build_reminder
    @invoice.company_id = params[:company_id] unless params[:company_id].nil?
  end

  def pay
    @invoice = current_account.invoices.find(params[:id])
    if @invoice.pay(invoice_params[:total_payed])
      flash[:notice] = "Pago registrado correctamente."
      flash[:notice] << "\nVenta cerrada." if @invoice.closed?
      redirect_to @invoice
    else
      flash[:error] = "No pudimos registrar el pago."
      redirect_to @invoice
    end
  end

  def show
    @invoice = @current_account.invoices.includes(:reminder, :invoice_items, :account, :company,comments: [:author, :attachments ], attachments: [:author]).find(params[:id])
    @invoice_items = @invoice.invoice_items
    @comments = @invoice.comments
    @attachments = @invoice.all_attachments
    @dtes = @invoice.dtes if @invoice.has_dte?
    @comment = @invoice.comments.build(author_id: current_user.id, author_type: current_user.class.to_s)
  end

  private
    def invoice_params
      params.require(:invoice).permit(:id, :company_id, :po_number, :new_state, :subject,:number, :active_date, :total_payed,
      :due_days, :currency, :contact_id, :taxed,invoice_items_attributes: [:id, :type, :description, :quantity, :price, :total, :_destroy],
        reminder_attributes: [:notification_date, :subject, :message, :active, :id],
        attachments_attributes: [:name, :category, :resource])
    end

    def prices_to_numbers
      return params if params["invoice"]["invoice_items_attributes"].nil?
      params["invoice"]["invoice_items_attributes"].each do |key,value|
        price = params["invoice"]["invoice_items_attributes"][key]["price"].to_s.gsub(/\$\s+/,"").gsub(/\./,"").gsub(/,/,".").to_f
        params["invoice"]["invoice_items_attributes"][key]["price"] = price
      end
      params
    end

    def invalid_dte(exception)
      flash[:error] = "No se puede generar el DTE.<p>#{exception.message}</p>".html_safe
      redirect_to @invoice
    end



end

app/helpers/invoices_helper.rb
module InvoicesHelper
  
  def activation_requirements_message(invoice)
    fields = Array.new
    fields << "número válido" unless invoice.has_number?
    fields << "contacto" unless invoice.has_contact?
    fields << "factura en pdf" unless invoice.has_invoice_attachment?
    fields.join(", ")
  end
  
  def change_invoice_state_menu(invoice)
    case invoice.status
    when "draft"
      "Activar venta"
    when "active"
      "Recibir pago"
    end
  end
  
  def display_input_or_value_for(f, value=nil)
    return "<td style='height: 35px'><div class='value'>value</div></td>".html_safe if params[:action] == "show"
    "<td>#{f.text_field value }</td>".html_safe
  end
  
  
  def display_select_or_value_for(f, value=nil,array)
    f.select value, options_for_select(array) unless params[:action] == "show"
  end
  
  def display_invoice_status(invoice)
    status = I18n.t "invoice.#{@invoice.status}"
    status.humanize.gsub(/dte/, "DTE...")
  end
  
  def input_disabled?
    return "disabled" if params[:action] == "show"
  end
  
  def invoice_item_types_for_select()
    InvoiceItem.types.map {|ii| ii.titleize}
  end
  
  def invoice_tax_label(invoice)
    return "Afecta" if invoice.taxed?
    return "Exenta"
  end
  
  # TODO: Hacer esto unnobstrusive
  def link_to_add_invoice_item_fields(name, f, association, partial_folder, locals={})
    #debug f.object.class.reflect_on_association(association.to_sym).klass.new
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "_replaceme_") do |builder|
      render(partial_folder + "/" + association.to_s.singularize + "_fields", locals.merge!(:f => builder))
    end
    link_to_function(name, ("add_invoice_item_fields(this,\"#{association}\", \"#{escape_javascript(fields.html_safe)}\")").html_safe)
  end
  
  
  def totals_resume_invoices_row(status, total)
    status_text = I18n.t "invoice.#{status}".pluralize
    total_text = number_to_currency(total)
    checked = checkbox_status_checked?(status)
    
		"<tr class='invoices-#{status}'>
			<td class="">
				<label class='checkbox'>
              #{ check_box_tag 'search[status]', status, checked }
				       #{status_text.titleize}
				    </label>
			</td>
			<td class='total-amount'>#{total_text}</td>
		</tr>".html_safe
  end
  
  def suggested_number(invoice)
    return invoice.number if invoice.active? && !invoice.nil?
    return invoice.suggested_number
  end
  
  def number_for_invoice(invoice)
    number = current_account.e_invoice_enabled? ? invoice.suggested_number : invoice.number
    number_field_tag(:number, number, data: {"validation-number-message" => "Tiene que ser un numero"})
  end
  
  def suggested_active_date(invoice)
    return l invoice.active_date unless invoice.active_date.nil?
    return l Date.today
  end
  
  def checkbox_status_checked?(status)
    return false if params["search"].nil?
    return false if params["search"]["status"].nil?
    return params["search"]["status"] == status
  end
  
  def index_invoice_number_display(invoice)
    return "id-#{invoice.id}" if invoice.number.nil?
    "##{invoice.number}"
  end
  
  
end

app/views/invoices/show_partials/_activate_modal.html.erb
<% content_for :form_errors do %>
<% end %>
<div id="<%= "activate-invoice-#{@invoice.id}-modal" %>" class="modal fade" style="display: none;">
 <%= form_for @invoice, url: activate_invoice_path(@invoice) do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Activar venta</h4>
      </div>
      <div class="modal-body">
			<div class="alert">
				<p><strong>Confirme el número de la factura</strong></p>
				<%= number_for_invoice(@invoice) %>
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		<%= f.submit 'Activar',  class: "btn btn-primary" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
  <% end %>
</div><!-- /.modal -->

app/views/invoices/show_partials/_cancel_modal.html.erb
<div id="<%= "cancel-invoice-#{@invoice.id}-modal" %>" class="modal fade confirmation-modal" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <span >¿Seguro que quieres anular esta venta?</span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">No, cancelar</button>
		<%= link_to 'Sí, anular venta',  cancel_invoice_path(@invoice),  method: :patch, class: "btn btn-danger" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/invoices/show_partials/_delete_modal.html.erb
<div id="<%= "delete-invoice-#{@invoice.id}-modal" %>" class="modal fade confirmation-modal" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <span >¿Seguro que quieres borrar esta venta?</span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">No, cancelar</button>
		<%= link_to 'Sí, borrar venta',  @invoice,  method: :delete, class: "btn btn-danger" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/invoices/show_partials/_pay_modal.html.erb
<div id="<%= "pay-invoice-#{@invoice.id}-modal" %>" class="modal fade" style="display: none;">
	<%= form_for @invoice, url: pay_invoice_path(@invoice) do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Registrar pago</h4>
      </div>
      <div class="modal-body">
		<div class="input-prepend input-append">
		  <span class="add-on">Pagar</span>
		  <%= f.text_field :total_payed, value: "#{@invoice.debt.to_i}", class: "span2 currency", autofocus: true %>
		  <span class="add-on">de</span>
		  <span class="add-on" style="width: 150px; text-align: left; padding-left: 10px;" id="debt" data-debt="<%= @invoice.debt.to_i %>"> <%= number_with_delimiter @invoice.debt.to_i %> </span>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		<%= f.submit 'Pagar total',  class: "btn btn-primary" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
  <% end %>
</div><!-- /.modal -->

app/views/invoices/show_partials/_sidebar_total.html.erb
<div id="invoice-total" class="invoice-status-<%= @invoice.status %>">
	<h3><%= number_to_currency(@invoice.total)%></h3>
	<%= render partial: "invoices/shared/invoice_advance_debt", locals: {invoice: @invoice} %>
</div>