config/routes.rb
Folio::Application.routes.draw do
  # Handle incoming email
  mount_griddler
  
  # Handle users authentication
  devise_for :users, :path_names => {:sign_up => "register"}
  devise_scope :user do
    constraints(Subdomain) do
      get "/login" => "devise/sessions#new"
    end
  end
  get 'accounts/check_subdomain' => 'accounts#check_subdomain', :as => :check_subdomain
  
  #Restricted to subdomain
  constraints(Subdomain) do
    get 'contacts/new_from_modal' => 'contacts#new_from_modal', :as => :new_contact_from_modal
    get 'accounts/check_invoice_number_availability' => 'accounts#check_invoice_number_availability', as: :check_invoice_number_availability
    get 'invoices/:id/activate_from_modal' => 'invoices#activate_from_modal', :as => :activate_invoice_from_modal
    patch 'invoices/:id/change_status' => 'invoices#change_status', :as => :change_invoice_status
    patch 'invoices/:id/cancel' => 'invoices#cancel', :as => :cancel_invoice
    patch 'invoices/:id/pay' => "invoices#pay", :as => :pay_invoice
    patch 'invoices/:id/activate' => "invoices#activate", :as => :activate_invoice
    get 'invoices/:id/clone' => "invoices#clone", :as => :clone_invoice
    get 'invoices/:id/attachments', to: redirect("/invoices/%{id}#invoice-attachments")
    get 'dtes/status/:invoice_id' => "dtes#status", as: :status
    resources :accounts, :only => [:show, :edit, :index, :update, :check_invoice_number_availability] do

    end
    resources :dtes
    resources :expenses
    resources :users
    resources :contacts
    resources :comments
    resources :attachments
    resources :companies do
      get 'invoices', :on => :member
      get 'contacts', :on => :member
      get 'expenses', :on => :member
    end
    resources :invoices do
      get :autocomplete_company_name, :on => :collection
      collection do
        get 'active'
        get 'draft'
        get 'due'
      end
    end
    resources :money_accounts
    get '/dashboard' => 'accounts#dashboard', :as => :dashboard
    root :to => "accounts#dashboard"
  end
  
  resources :accounts, :only => [:new, :create] , :constraints => { :subdomain => /(app|www|folio)/ }
  
end

app/views/shared/_account_menu.html.erb
<div class="account-menu">
	<ul class="inline pull-right">
		<li><%= link_to "Mi Empresa", account_path(current_account) %></li>
		<li><%= link_to "Mis Datos", user_path(current_user) %></li>
		<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
	</ul>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>" >
    	<a class="close" data-dismiss="alert">×</a>
		<p>
			<%= msg %>
		</p>
		<%= yield :form_errors %>
  	</div>
<% end %>

app/views/shared/_indicadores.html.erb
<div class="span6">
<% cache "money-indicators", expires_in: 30.minutes do %>
	<ul class="inline money-indicators">
		<li id="usd-conversion-rate" data-value="<%= get_indicator_value_for 'dolar' %>">Dólar: <%=number_to_currency get_indicator_value_for("dolar"), precision: 2 %></li>
		<li id="uf-conversion-rate" data-value="<%= get_indicator_value_for 'uf' %>">UF: <%= number_to_currency get_indicator_value_for("uf"), precision: 2 %></li>	
	</ul>
	<span id="clp-conversion-rate" data-value="1" />
<% end %>
</div>

app/views/shared/_modal.html.erb
<div id="<%= "#{options[:id]}-modal" %>" class="modal fade" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><%= options[:title] %></h4>
      </div>
      <div class="modal-body">
        <%= options[:body] %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		<button type="button" class="btn btn-primary">Guardar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_modal_form.html.erb
<div id="<%= "#{options[:id]}-modal" %>" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><%= options[:title] %></h4>
      </div>
	  <% flash.each do |name, msg| %>
	  	<div class="alert alert-<%= name == :notice ? "success" : "error" %>" >
	      	<a class="close" data-dismiss="alert">×</a>
	      	<%= msg %>
	  		<br/>
	  		<%= yield :form_errors %>
	    	</div>
	  <% end %>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		<% if options[:method] == "edit" %>
			<button type="button" class="btn btn-primary" data-submit="submit" data-formid="<%= "#{options[:method]}_#{options[:object]}_#{options[:object_id]}" %>">Guardar</button>
		<% else %>
			<button type="button" class="btn btn-primary" data-submit="submit" data-formid="<%= "#{options[:method]}_#{options[:object]}" %>">Guardar</button>
		<% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_navbar.html.erb
<div class="navbar-header container">
	<div class="navbar pre-main-navbar">
		<%= render :partial => "shared/indicadores" %>
		<%= render :partial => "shared/account_menu" %>
	</div>

	<div class="navbar navbar-inverse">
		<div class="navbar-inner">
			<div class="container pull-right">
				<a class="brand" href="#"><%= image_tag "logos/folio_logo.png", :title => "Logo de Folio", :class => "pull-right" %></a>
			</div>
		</div>

	</div>
	<div id="main-navbar" >
		<div class="nav nav-tabs">
		   	<%= navbar_menu_link("Indicadores", dashboard_url) %>
			  <%= navbar_menu_link("Ventas", invoices_url) %>
			  <!-- <li><a href="#">Compras</a></li>
			  <li><a href="#">Finanzas</a></li> -->
				<%= navbar_menu_link("Cuentas", money_accounts_url) %>
			  <%= navbar_menu_link("Empresas", companies_url) %>
		</div>
	</div>
</div>

app/views/shared/_sub_navbar.html.erb
<div class="navbar-header container sub-navbar">
	<% if content_for?(:sub_navbar)%>
		<div class="navbar">
			<%= yield :sub_navbar %>
		</div>
	<% end %>
</div>

app/views/shared/_sub_navbar_search.html.erb
<%= form_tag form_path, method: "get", remote: true do %>
	<%= text_field_tag text_field_tag , nil, :class => "search",
	:placeholder => placeholder , :autofocus => true %>		
<% end %>