config/routes.rb
Folio::Application.routes.draw do
  # Handle incoming email
  mount_griddler
  
  # Handle users authentication
  devise_for :users, :path_names => {:sign_up => "register"}
  devise_scope :user do
    constraints(Subdomain) do
      get "/login" => "devise/sessions#new"
    end
  end
  get 'accounts/check_subdomain' => 'accounts#check_subdomain', :as => :check_subdomain
  
  #Restricted to subdomain
  constraints(Subdomain) do
    get 'contacts/new_from_modal' => 'contacts#new_from_modal', :as => :new_contact_from_modal
    get 'accounts/check_invoice_number_availability' => 'accounts#check_invoice_number_availability', as: :check_invoice_number_availability
    get 'invoices/:id/activate_from_modal' => 'invoices#activate_from_modal', :as => :activate_invoice_from_modal
    patch 'invoices/:id/change_status' => 'invoices#change_status', :as => :change_invoice_status
    patch 'invoices/:id/cancel' => 'invoices#cancel', :as => :cancel_invoice
    patch 'invoices/:id/pay' => "invoices#pay", :as => :pay_invoice
    patch 'invoices/:id/activate' => "invoices#activate", :as => :activate_invoice
    get 'invoices/:id/clone' => "invoices#clone", :as => :clone_invoice
    get 'invoices/:id/attachments', to: redirect("/invoices/%{id}#invoice-attachments")
    get 'dtes/status/:invoice_id' => "dtes#status", as: :status
    resources :accounts, :only => [:show, :edit, :index, :update, :check_invoice_number_availability] do

    end
    resources :dtes
    resources :expenses
    resources :users
    resources :contacts
    resources :comments
    resources :attachments
    resources :companies do
      get 'invoices', :on => :member
      get 'contacts', :on => :member
      get 'expenses', :on => :member
    end
    resources :invoices do
      get :autocomplete_company_name, :on => :collection
      collection do
        get 'active'
        get 'draft'
        get 'due'
      end
    end
    resources :money_accounts
    get '/dashboard' => 'accounts#dashboard', :as => :dashboard
    root :to => "accounts#dashboard"
  end
  
  resources :accounts, :only => [:new, :create] , :constraints => { :subdomain => /(app|www|folio)/ }
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :account
  has_many :invoices
  has_many :contacts
  
  scope :for_account, -> {where(account_id: Account.current_id)}
  
  has_attached_file :avatar, :styles => { :large => "300x300>", :medium => "150x150>", :thumb => "60x60>" }, default_url: :default_avatar_url
  validates_presence_of :rut, :name, :address, :province, :city, :account_id, :industry
  validates_uniqueness_of :rut, :scope => [:account_id]
  validates_with RutValidator
  
  before_destroy :check_if_empty
  
  def empty?
    !invoices.any?
  end
  
  def contacts_in_alphabetycal_order(contact_name_like)
    return contacts.order("name") if contact_name_like.nil?
    contacts.where('name LIKE ?', "%#{contact_name_like}%")
  end
  
  def default_avatar_url
    identicon = generate_identicon
    "data:image/png;base64,#{identicon}"
  end
  
  def generate_identicon
    key = name.nil? ? random_string : name + "1234567891011121314"
    blob = RubyIdenticon.create("RubyIdenticon", key: key)
    Base64.strict_encode64 blob
  end
  
  def has_invoices?
    invoices.any?
  end

  def has_contacts?
    contacts.any?
  end
  
  def self.in_alphabetycal_order(company_name_like)
    return order("name") if company_name_like.nil?
    where('name LIKE ?', "%#{company_name_like}%")
  end

  def invoices_search(params)
    invoices.search(params)
  end
  
  def invoices_due_total
    20090203
  end
  
  def sales_total
    209093293
  end
  
  def payment_grade
    4.5
  end
  
  def payment_days_median
    return nil if empty?
    return nil if invoices.closed.empty?
    invoices.closed.map {|i| i.payment_days}.median.round
  end
  
  # Esto es para buscar por rut o id en 
  # invoices_controller
  # http://masev.folio4.dev/companies/12454782-2/invoices.json
  def self.find_by_id_or_rut(value)
    if value.match(/-/)
      result = where(rut: format_rut(value)).first
      fail ActiveRecord::RecordNotFound if result.nil?
      result
    else
      find(value)
    end
  end
  
  def self.format_rut(raw_rut)
    rut = raw_rut.to_s.delete '.-'
    if rut.nil? || rut.empty?
      return rut
    end
    rut_end = rut[rut.length - 1, rut.length]
    rut_init_temp = rut[0, rut.length - 1]
    rut_init = ''
    while rut_init_temp.length > 3 do
      rut_init = '.' + rut_init_temp[rut_init_temp.length - 3, rut_init_temp.length] + rut_init
      rut_init_temp = rut_init_temp[0, rut_init_temp.length - 3]
    end
    rut = rut_init_temp+rut_init+'-'+rut_end
    rut.upcase
  end    
    
  def total_due
    invoices.due.to_a.sum(&:total).to_i
  end
  
  def total_active
    invoices.active.to_a.sum(&:total).to_i
  end
  
  def total_closed
    invoices.closed.to_a.sum(&:total).to_i
  end
  
  def total_draft
    invoices.draft.to_a.sum(&:total).to_i
  end
  
  private
  def random_string
    (0...17).map{ ('a'..'z').to_a[rand(26)] }.join
  end
  
  def check_if_empty
    empty?
  end  
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = current_account.companies_in_alphabetycal_order(params[:company_name_like])
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def invoices
    @company = current_account.companies.find_by_id_or_rut(params[:id])
    params[:search] = {company_id: @company.id}
    @invoices_total_resume = @company.invoices_search(params[:search])
    @invoices = @invoices_total_resume.page(params[:page])
    @invoices = @invoices.where.not(aasm_state: params[:exclude]) if params[:exclude]
    @search_params = params.to_param
  end

  def expenses
    @company = current_account.companies.find(params[:id])
  end

  def contacts
    @company = current_account.companies.find(params[:id])
    @contacts = @company.contacts_in_alphabetycal_order(params[:contact_name_like])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.account_id = current_account.id
    if @company.save
      flash[:notice] = "Empresa guardada correctamente."
      redirect_to company_path(@company)
    else
      render "new"
    end
  end

  def update
    @company = current_account.companies.find(params[:id])
    if @company.update_attributes(company_params)
      flash[:notice] = "Empresa guardada correctamente."
      redirect_to company_path(@company)
    else
      render "edit"
    end
  end

  def edit
    @company = current_account.companies.find(params[:id])
  end

  def destroy
    @company = current_account.companies.find(params[:id])
    if @company.destroy
      flash[:notice] = "Empresa eliminada correctamente"
      redirect_to companies_path()
    else
      flash[:error] = "No se puede eliminar esta empresa"
      redirect_to @company
    end
  end

  def show
    @company = current_account.companies.find_by_id_or_rut(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end


  private
    def company_params
      params.require(:company).permit(:avatar, :name, :city, :address, :province, :rut, :company_name_like, :industry)
    end


end

app/helpers/companies_helper.rb
module CompaniesHelper
  
  def display_company_avatar(company, size = :medium)
    content_tag(:img, nil,:src => company.avatar.url(size))
  end
  
  def company_label_customer(company)
    return unless company.has_invoices?
    content_tag(:span, "cliente", :class => "label label-customer")
  end
  
  def company_label_provider(company)
    return unless company.has_invoices?
    content_tag(:span, "proveedor", :class => "label label-provider")
  end
  
  def payment_days_message(company)
    return unless company.payment_days_median
    message = "Paga generalmente con <strong>#{company.payment_days_median} días de atraso</strong>"
    message = "Cliente siempre paga al día" if company.payment_days_median < 1
    content_tag :div, class: "pull-right totals-kpi-box-header" do 
      content_tag :h5, class: "payment-days-message" do
        message.html_safe
      end
    end
  end
  
  
end

app/views/companies/_companies_search.html.erb
<div class="action-links pull-right">
	<%= link_to content_tag(:i, nil, :class => "icon-plus icon-white").html_safe+" Agregar Empresa", new_company_path(), :class => "btn btn-success" %>	
</div>

<%= form_tag companies_path(), method: "get", remote: true do %>
	<%= text_field_tag "company_name_like", nil, :class => "search",
	:placeholder => "Buscar empresa", :autofocus => true %>		
<% end %>

app/views/companies/_company.html.erb
<li class="company">
	<div class="company-box">
			<h4>
				<%= link_to company.name, company_path(company) %>
				<br><small><%= company.rut %></small>
			</h4>
			<ul class="company-contact-info">
				<li><%= company.address %></li>
				<li><%= company.city %> </li>
				<li><%= company.phone %> </li>
			</ul>
			<div class="footer">
			</div>
	</div>
</li>

app/views/companies/_company_info.html.erb
<section>	
	<div class="row">
		<div class="span4 pull-right totals-kpi-box">
				<div class="totals-kpi-box-header">
					<h5>Información de Contacto</h5>
				</div>
				<div class="row  totals-kpi-box-body">
					<ul class="unstyled">
						<li><%= @company.rut %></li>
						<li><%= @company.address %></li>
						<li><%= @company.province %> - <%= @company.city %> </li>
						<li><%= @company.phone %>
					</ul>
					<br>
				</div>
		</div>
		<div class="row span7 totals-kpi-box">
			<%= payment_days_message(@company) %>
				<div class="totals-kpi-box-header">
					<h5>Ventas</h5>
				</div>
				<div class="row span7 totals-kpi-box-body">
					<% unless @company.invoices.any? %>
						<div class="alert alert-block blank-slate" style="min-height: 0px; border: 1px dashed gray; padding-bottom: 40px">
							<div class="blank-slate-text">
								<p>
									Aun no tienes ventas para esta Empresa, pero cuando las tengas aquí podrá ver un resumen de éstas.
								</p>
							</div>
						</div>
					<% else %>
						<div class="total-kpi">
							<span class="total-kpi-title invoice-active">Activas</span>
							<div class="total-kpi-value">
								<%= number_to_currency @company.total_active %>
							</div>
						</div>
						<div class="total-kpi">
							<span class="total-kpi-title invoice-due">Vencidas</span>
							<div class="total-kpi-value">
								<%= number_to_currency @company.total_due %>
							</div>
						</div>
						<div class="total-kpi">
							<span class="total-kpi-title invoice-closed">Ventas totales</span>
							<div class="total-kpi-value">
								<%= number_to_currency @company.total_closed %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
			
			<!-- <div class="span7 totals-kpi-box">
				<div class="totals-kpi-box-header">
					<h5>Pagos</h5>
				</div>
				<div class="row span7 totals-kpi-box-body">
					<div class="total-kpi">
						<span class="total-kpi-title">Activos</span>
						<div class="total-kpi-value">$ 0</div>
					</div>
					<div class="total-kpi">
						<span class="total-kpi-title">Vencidos</span>
						<div class="total-kpi-value">$ 645.334</div>
					</div>
					<div class="total-kpi">
						<span class="total-kpi-title">Debemos</span>
						<div class="total-kpi-value">$ 645.334</div>
					</div>
				</div>
			</div> -->
				
		</div>
	</div>

</section>

app/views/companies/_index.html.erb
<% content_for :sub_navbar do %>

	<div class="action-links pull-right">
		<%= search_add_record_link(new_company_path, "Agregar Empresa") %>
	</div>
	
	<%= render :partial => "shared/sub_navbar_search", locals: {
	form_path: companies_path, text_field_tag: "company_name_like",
	placeholder: "Buscar empresa"} %>
		
<% end %>

<div class="row document">
	<section>
		<%= render :partial => "companies_empty" unless current_account.companies.any? %>
			<ul class="companies inline" id="companies_boxes">
				<%= render :partial => "company", :collection => @companies %>
			</ul>
	</section>
</div>

app/views/companies/_show.html.erb
<% content_for :sub_navbar do %>
	<div class="action-links pull-right">
		<ul class="inline">
				<li>
					<%= link_to "#{fa_icon "plus"} Nueva Venta".html_safe, new_invoice_path(:company_id => @company.id) %>
				</li>
				<!-- <li>
					<%= link_to " Nueva Compra", edit_company_path(@company) %>
				</li> -->
				<li>
					<%= link_to "#{fa_icon "edit"} Editar empresa".html_safe, edit_company_path(@company) %>
				</li>
				<% if @company.empty? %>
					<li>
						<%= link_to "#{fa_icon "trash-o"} Borrar empresa".html_safe, "#", data: {toggle: "modal", target: "#delete-company-#{@company.id}-modal"}, class: "invoices-due"  %>
					</li>
				<% end %>
			</ul>
	</div>
	<h3><%= @company.name %> <small><%= @company.industry %></small></h3>
<% end %>

app/views/companies/contacts.html.erb
<%= render "show" %>

<%= render partial: "companies/shared/navbar" %>

<%= render_modal_form(
	id: "company-contact",
	title: "Agregar contacto",
	body: "",
	method: "new",
	object: "contact") 
%>

<%= render_modal_form(
	id: "edit-company-contact",
	title: "Editar contacto",
	body: "",
	method: "edit",
	object: "contact") 
%>

<div class="row document">

	<div id="company-contacts" class="span12" style="">
		<div class="action-links pull-right">
			<%= search_add_record_link(new_contact_from_modal_path(company_id: @company.id), "Agregar Contacto", {toggle: "modal", target: "#company-contact-modal"}) %>
		</div>
	
		<%= render :partial => "shared/sub_navbar_search", locals: {
		form_path: contacts_company_path(@company.id), text_field_tag: "contact_name_like",
		placeholder: "Buscar contacto"} %>		
	</div>
	
	<%= render :partial => "companies/shared/contacts_empty" unless @company.contacts.any? %>
	
	<section>
			<ul class="companies inline" id="contacts_boxes">
				<%= render :partial => "companies/shared/contact", :collection => @contacts %>
			</ul>
	</section>

</div>

app/views/companies/contacts.js.erb
$("#contacts_boxes").empty();
$("#contacts_boxes").hide();
$("#contacts_boxes").append('<%= j render partial: "companies/shared/contact", :collection => @contacts %>').fadeIn(1000);

app/views/companies/edit.html.erb
<div class="row document">
	<section>
		<header class="section-header">
			<h3>Editar Empresa</h3>
		</header>
		
		<%= render :partial => 'company_form' %>

		
	</section>
</div>

app/views/companies/expenses.html.erb
<%= render "show" %>

<%= render partial: "companies/shared/navbar" %>


<div class="row document">
	
	<div class="span8">
		
	</div>
	<div id="side-menu" class="span3" style="margin-top: 14px">
		
	</div>
</div>

app/views/companies/index.html.erb
<%= render "index" %>

app/views/companies/index.js.erb
$("#companies_boxes").empty();
$("#companies_boxes").hide();
$("#companies_boxes").append('<%= j render partial: "company", :collection => @companies %>').fadeIn(1000);

app/views/companies/invoices.html.erb
<%= render "show" %>

<%= render partial: "companies/shared/navbar" %>



<div class="row document">
	
	<div class="span8">
		<div style="border-bottom: 1px solid #ddd">
			<%= render partial: "invoices/shared/subnav_sorter", locals: {search_params: @search_params} %>
		</div>
		<div id="invoices">
			<%= render partial: "invoices/invoices_table", locals: {invoices: @invoices} %>
		</div>
		<% if @invoices.size < 1%>
			<div class="alert alert-block blank-slate" style="min-height: 0px; border: 1px dashed gray; padding-bottom: 40px">
				<div class="blank-slate-text">
					<p>
						Aun no tienes ventas para esta Empresa, pero cuando las tengas apareceran aquí.
					</p>
				</div>
			</div>
		<% end %>
	</div>
	<div id="side-menu" class="span3" style="margin-top: 14px">
		<%= form_tag invoices_path(), id: "status_search", method: :get, remote: true do |f|%>
			<%= render partial: "invoices/sidebar/invoice_total_resume", locals: {invoices: @invoices} %>
			<%= hidden_field_tag "search[query_items][company_id]", @company.id %>
		<% end %>
	</div>
</div>

app/views/companies/new.html.erb
<% content_for :sub_navbar do %>
	<h3>Agregar Empresa</h3>
<% end %>

<div class="row document">
	<section>
		
		<%= render :partial => 'company_form' %>

		
	</section>
</div>

app/views/companies/show.html.erb
<%= render partial: "companies/show_partials/delete_modal" if @company.empty? %>
<%= render "show" %>

<%= render partial: "companies/shared/navbar" %>

<div class="row document">
	<%= render :partial => 'company_info' %>
</div>