config/routes.rb
Folio::Application.routes.draw do
  # Handle incoming email
  mount_griddler
  
  # Handle users authentication
  devise_for :users, :path_names => {:sign_up => "register"}
  devise_scope :user do
    constraints(Subdomain) do
      get "/login" => "devise/sessions#new"
    end
  end
  get 'accounts/check_subdomain' => 'accounts#check_subdomain', :as => :check_subdomain
  
  #Restricted to subdomain
  constraints(Subdomain) do
    get 'contacts/new_from_modal' => 'contacts#new_from_modal', :as => :new_contact_from_modal
    get 'accounts/check_invoice_number_availability' => 'accounts#check_invoice_number_availability', as: :check_invoice_number_availability
    get 'invoices/:id/activate_from_modal' => 'invoices#activate_from_modal', :as => :activate_invoice_from_modal
    patch 'invoices/:id/change_status' => 'invoices#change_status', :as => :change_invoice_status
    patch 'invoices/:id/cancel' => 'invoices#cancel', :as => :cancel_invoice
    patch 'invoices/:id/pay' => "invoices#pay", :as => :pay_invoice
    patch 'invoices/:id/activate' => "invoices#activate", :as => :activate_invoice
    get 'invoices/:id/clone' => "invoices#clone", :as => :clone_invoice
    get 'invoices/:id/attachments', to: redirect("/invoices/%{id}#invoice-attachments")
    get 'dtes/status/:invoice_id' => "dtes#status", as: :status
    resources :accounts, :only => [:show, :edit, :index, :update, :check_invoice_number_availability] do

    end
    resources :dtes
    resources :expenses
    resources :users
    resources :contacts
    resources :comments
    resources :attachments
    resources :companies do
      get 'invoices', :on => :member
      get 'contacts', :on => :member
      get 'expenses', :on => :member
    end
    resources :invoices do
      get :autocomplete_company_name, :on => :collection
      collection do
        get 'active'
        get 'draft'
        get 'due'
      end
    end
    resources :money_accounts
    get '/dashboard' => 'accounts#dashboard', :as => :dashboard
    root :to => "accounts#dashboard"
  end
  
  resources :accounts, :only => [:new, :create] , :constraints => { :subdomain => /(app|www|folio)/ }
  
end

app/models/account.rb
class Account < ActiveRecord::Base
  USERS_COUNT_MIN = 1

  has_many :users, :dependent => :destroy
  has_many :invoices, :dependent => :destroy
  has_many :expenses, :dependent => :destroy
  has_many :audits, :dependent => :destroy
  has_many :companies, :dependent => :destroy
  has_many :contacts, through: :companies
  has_many :attachments, :dependent => :destroy
  has_many :dtes, :dependent => :destroy
  has_many :money_accounts, dependent: :destroy
  accepts_nested_attributes_for :users, :allow_destroy => true

  validates_uniqueness_of :subdomain
  validates_presence_of :subdomain, :name
  validates_format_of :subdomain, :with => /^((?!^(www|folio|app|dev)).)*$/i, :message => "No puedes usar ese nombre", multiline: true
  validate :check_users_number # The account must have at least one user
  validates_presence_of :industry, :if => :e_invoice_enabled?
  validates_presence_of :industry_code, :if => :e_invoice_enabled?
  #validates_presence_of :e_invoice_resolution_date, :if => :e_invoice_enabled?

  after_save :initialize_account
  before_validation :clear_subdomain

  def self.per_page

  end

  def self.subdomain_available?(subdomain)
    return false if "/^((?!^(www|folio|app|dev)).)*$/i".match(subdomain)
    !exists?(:subdomain => subdomain.downcase)
  end

  def check_invoice_number_availability(number, taxed)
    value = number.to_i
    return !invoices.not_draft.taxed.where(number: value).any? if taxed.to_s == "true"
    return !invoices.not_draft.not_taxed.where(number: value).any?
  end

  def invoice_last_used_number(taxed = false)
    unless invoices.not_draft.any?
      return (dte_invoice_start_number - 1) if e_invoice_enabled? && taxed
      return (dte_invoice_untaxed_start_number - 1) if e_invoice_enabled? && !taxed
      return 0
    end
    #invoices.not_draft.select(:number).order("number desc").limit(1).first.number
    result = 0
    if taxed
      result = invoices.open.taxed.order("number desc").select(:number).limit(1).first
    else
      result = invoices.open.not_taxed.order("number desc").select(:number).limit(1).first
    end
    result.nil? ? 0 : result.number
  end

  def last_used_dte_nc_number
    return (dte_nc_start_number - 1) unless has_dte_nc?
    dtes.dte_ncs.last.folio
  end

  def has_dte_nc?
    dtes.dte_ncs.any?
  end

  def owner
    User.find(owner_id)
  end

  def contact_info_complete?
    attributes.detect {|k,v| v.blank? unless k == "e_invoice_enabled" }.nil?
  end

  def companies_in_alphabetycal_order(company_name_like)
    companies.in_alphabetycal_order(company_name_like)
  end

  def owner_name
    owner.full_name
  end

  def trial?
    plan_id == Plan.trial.id
  end

  def has_data?
    invoices.any? || expenses.any?
  end

  def has_invoices?
    invoices.any?
  end

  def invoices_search(params)
    invoices.search(params)
  end


  Invoice::STATUS_NAME.each do |status|
    define_method "#{status}_invoices" do
      self.invoices.send(status)
    end
  end


  def self.current_id=(id)
    Thread.current[:tenant_id] = id
  end

  def self.current_id
    Thread.current[:tenant_id]
  end

  # Invoice totals
  def total_due
    invoices.total_due
  end

  def total_active
    invoices.total_active
  end

  def total_closed
    invoices.total_closed
  end

  def total_draft
    invoices.total_draft
  end

  def users_emails_array
    users.map {|u| u.email}
  end

  private

    def users_count_valid?
      users.length >= USERS_COUNT_MIN
    end

    def check_users_number
      unless users_count_valid?
        errors.add(:base, :users_too_short, :count => USERS_COUNT_MIN)
      end
    end

    def initialize_account
      set_owner
      set_trial_plan
    end

    def set_owner
      update_column("owner_id", self.users.last.id) if owner_id.nil?
    end

    def set_trial_plan
      update_column("plan_id", Plan.trial.id) if plan_id.nil?
    end

    def clear_subdomain
      subdomain.split(/\./).join("")
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:new, :create, :check_subdomain]
  before_action :validate_owner!, :only => ['edit', 'update']
  respond_to :html, :xml, :json

  def dashboard

  end
  
  def check_invoice_number_availability
    valid = current_account.check_invoice_number_availability(params[:value],params[:taxed])
    respond_to do |format| 
      format.html {render :json => ""}
      format.json {render :json => {value: params[:value].to_i, valid: valid, message: "Número ya en uso"}}
    end 
  end

  def new
    @account = Account.new
    @account.users.build
  end

  def show
    @account = current_account
  end

  def edit
    @account = current_account
  end

  def update
    @account = Account.find(current_account)
    if @account.update_attributes(account_params)
      flash[:notice] = "Información actualizada correctamente."
      redirect_to account_url(@account, :subdomain => @account.subdomain)
    else
      render :action => "edit"
    end
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      AccountMailer.delay.register_welcome(@account.owner.id)
      flash[:notice] = "Cuenta creada correctamente, bienvenido a Folio"
      sign_in(:user, @account.owner)
      redirect_to root_url(:subdomain => @account.subdomain)
    else
      render 'new'
    end
  end

  def check_subdomain
    subdomain_availability = Account.subdomain_available?(subdomain_params)
    respond_to do |format|
      format.json {render :json => subdomain_availability.to_json}
    end
  end

  private

    def account_params
      params.require(:account).permit(:name, :city, :phone, :rut, :address, 
                  :subdomain, :country, :industry, :industry_code, :value,
                  :e_invoice_regional_address, :e_invoice_resolution_date,
                  users_attributes: [:email, :password])
    end

    def subdomain_params
      params.require(:name)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<section>
	<header class="section-header">
		<% if current_user.owner? %>
			<%= link_to "Editar información", edit_account_path(current_account), :class => "btn btn-small pull-right" %>
		<% end %>
		<h3>Mi Empresa</h3>
	</header>
	
	<div class="row">
		
		<%= render :partial => "account_info" %>
		
		<%= render :partial => 'account_stats_resume_box' %>
		
	</div>
	
</section>

app/views/accounts/_account_info.html.erb
<div class="span5 account-info">
	<h4>
		<%= @account.name.titleize %>
		<br/>
		<small><%= current_account.rut %></small>
		<% unless current_account.industry.empty? %>
			<br><small><%= current_account.industry.titleize %></small>
		<% end %>
	</h4>
	
	<address>
		<%= current_account.address %><br>
		<%= current_account.e_invoice_regional_address %> --> CAMBIARLO!!!</br>
		<%= "#{current_account.city} #{current_account.country}" %><br>
		<%= current_account.phone %><br>
	</address>
</div>

app/views/accounts/_account_stats_resume_box.html.erb
<div class="span4 well pull-right">
	<ul>
		<% if (!current_account.contact_info_complete? && current_user.owner?) %>
			<li>
				<strong><%= link_to "Completa los datos de tu empresa", edit_account_path(current_account) %></strong>
			</li>
		<% end %>
		<li>El dueño de la cuenta es <%= link_to current_account.owner_name, user_path(current_account.owner) %> </li>
		<% if current_account.e_invoice_enabled? %>
			<li>Puede emitir documentos electrónicos</li>
		<% end %>
	</ul>
</div>

app/views/accounts/_account_users.html.erb
<section>
	<header class="section-header">
		<% if current_user.owner? %>
			<%= link_to "Agregar usuario", new_user_path(current_account), :class => "btn btn-success btn-small pull-right" %>
		<% end %>
		<h3>Usuarios</h3>
	</header>
	
	<div class="row">
		
		<%= render :partial => current_account.users %>
		
	</div>
	
</section>

app/views/accounts/_dashboard_blank_slate.html.erb
<div class="alert alert-block blank-slate">
	<div class="blank-slate-example">
			<%= image_tag "blank_slates/folio_sales_example.png", :title => "Ejemplo de Ventas de Folio", :class => "img-polaroid" %>
	</div>
	
	<div class="blank-slate-text">
		<h3>Los indicadores muestran la salud de tu negocio</h3>
		<p>
			Una vez que comiences a ingresar ventas y gastos está página mostrará la salud de tu empresa. Datos tales como <strong>cuanto debes pagar</strong> este mes, <strong>cuanto debes cobrar</strong> y <strong>hasta cuando te alcanza</strong> el dinero que tienes.
		</p>
		<h4>¿Quieres conocer la salud de tu negocio?</h4>
		<p>
			Entonces ingresa tu <%= link_to "primera venta", new_invoice_path() %> o registra tu <%= link_to "primer gasto", new_expense_path() %>.
		</p>
	</div>
</div>

app/views/accounts/dashboard.html.erb
<% if current_account.has_data? %>
	<div style="background: white; border: 1px dashed gray; text-align: center; padding: 10px">
		<h2>Esto está en construcción</h2>
	</div>
	<%= render :partial => "dashboard_blank_slate" %>
<% else %>
	<%= render :partial => "dashboard_blank_slate" %>
<% end %>

app/views/accounts/edit.html.erb
<div class="row document">
	<section>
		<header class="section-header">
			<h3>Edita la información de tu Empresa</h3>
		</header>
		
		<%= simple_form_for @account, 
			:html => {:class => "form-horizontal"},  
			defaults: { input_html: { class: 'input-xlarge' } } do |f| %>

			  <%= f.input :name, label: false, required: true, placeholder: "Nombre", autofocus: true  %>
			  <%= f.input :rut, label: false, required: true, placeholder: "RUT" %>
			  <%= f.input :industry, label: false, placeholder: "Giro comercial" %>
			  <%= f.input :industry_code, label: false, placeholder: "Código de activdad económica" %>
			  <%= f.input :address, label: false, placeholder: "Dirección" %>
			  <%= f.input :city, label: false, placeholder: "Comuna" %>
			   <%= f.input :e_invoice_regional_address, label: false, placeholder: "Región" %>
			  <%= f.input :country, label: false, placeholder: "País" %>
			  <%= f.input :phone, label: false, placeholder: "Teléfono" %>
			  <% if @account.e_invoice_enabled? %>
			  	<%= f.input :e_invoice_resolution_date, label: false, placeholder: "Fecha de Resolución F. Electrónica", as: :string, input_html: {data: {"date-format" => "dd/mm/yyyy"}} %>
			  <% end %>
			
			
			  <div class="actions">
			    <%= f.button :submit, "Guardar", :class => "btn btn-success"  %>
				o <%= link_to "Cancelar", account_path(current_account) %>
			  </div>
			
		<% end %>
		
	</section>
</div>

app/views/accounts/new.html.erb
<div id="login-box">
	<h3>Regístrate para comenzar el trial</h3>
	<%= simple_form_for(@account, :html => {:class => "login-form form-vertical"}) do |f| %>
	<% if f.error_notification %>        
   		  <h4 class="error" style="margin-top: -20px; "><%= f.error_notification %></h4>
	<% else %>
		<p>30 días gratis para conocer Folio</p>
	<% end %>
	  <div class="inputs">
	  <%= f.simple_fields_for :users do |user_form| %>
			<div class="control-group">
		    <%= user_form.input :email, :required => true, :autofocus => true, :label => false, :placeholder => "Email",  :input_html => {:class => "login-field", data: {"validation-email-message" => "Email incorrecto"}} %>
			</div>
			<div class="control-group">
		    <%= user_form.input :password, :required => true, :label => false, :placeholder => "Contraseña",  :input_html => {:class => "login-field"} %>
			</div>
		<% end %>
		<div class="control-group">
	    <%= f.input :name, :required => true, :label => false, :placeholder => "Empresa",  :input_html => {:class => "login-field"} %>
		</div>
		<div class="control-group">
	    <%= f.input :subdomain, :label => false, :input_html => {:class => "login-field"}, :wrapper => :prepend do %>
		<%= f.input_field :subdomain, :required => true, :disabled => false, :class => "login-field", :placeholder => "empresa", data: {"validation-pattern-message" => "No puedes usar este subdominio"} %>
		<span class="folio-domain">.folio.cl</span>
		<% end %>
		</div>
		
	  </div>

	  <div class="actions">
	    <%= f.button :submit, "Comenzar trial", :class => "btn-large btn-block btn-primary"  %>
	  </div>
	<% end %>
</div>

app/views/accounts/show.html.erb
<div class="row document">
	<%= render :partial => 'account' %>
	<%= render :partial => 'account_users' %>
</div>